<?php
declare(strict_types=1);
namespace Domains\Diagnostic\Infrastructure\Persistence\MySql;
use Domains\Diagnostic\Application\Contract\MethodologyStudioRepositoryInterface;
use PDO;
final readonly class MysqlMethodologyStudioRepository implements MethodologyStudioRepositoryInterface
{
 public function __construct(private PDO $db){}
 public function activate(string $o,string $p,string $mv,int $v):void{$s=$this->db->prepare('UPDATE diagnostic_packs SET active_version=:v,active_methodology_version=:mv WHERE organization_id=:o AND pack_id=:p');$s->execute(['o'=>$o,'p'=>$p,'v'=>$v,'mv'=>$mv]);}
 public function packs(string $o):array{$s=$this->db->prepare('SELECT pack_id,MAX(name) name,MAX(target_domain) domain,MAX(active_version) active_version,MAX(active_methodology_version) active_methodology_version,MAX(updated_at) updated_at FROM diagnostic_packs WHERE organization_id=:o GROUP BY pack_id ORDER BY updated_at DESC');$s->execute(['o'=>$o]);return $s->fetchAll(PDO::FETCH_ASSOC);}
 public function pack(string $o,string $p):?array{$s=$this->db->prepare('SELECT pack_id,MAX(name) name,MAX(target_domain) domain,MAX(active_version) active_version,MAX(active_methodology_version) active_methodology_version,MAX(updated_at) updated_at FROM diagnostic_packs WHERE organization_id=:o AND pack_id=:p GROUP BY pack_id');$s->execute(['o'=>$o,'p'=>$p]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function savePack(string $o,array $p):void{$s=$this->db->prepare("INSERT INTO diagnostic_packs(organization_id,pack_id,version,name,target_domain,status,methodology_json,content_hash,lock_version) VALUES(:o,:p,1,:n,:d,'draft',JSON_OBJECT(),:h,0) ON DUPLICATE KEY UPDATE name=VALUES(name),target_domain=VALUES(target_domain)");$s->execute(['o'=>$o,'p'=>$p['id'],'n'=>$p['name'],'d'=>$p['domain'],'h'=>str_repeat('0',64)]);}
 public function versions(string $o,string $p):array{$s=$this->db->prepare('SELECT * FROM diagnostic_pack_versions WHERE organization_id=:o AND pack_id=:p ORDER BY created_at DESC');$s->execute(['o'=>$o,'p'=>$p]);return $s->fetchAll(PDO::FETCH_ASSOC);}
 public function version(string $o,string $p,string $v):?array{$s=$this->db->prepare('SELECT * FROM diagnostic_pack_versions WHERE organization_id=:o AND pack_id=:p AND methodology_version=:v');$s->execute(['o'=>$o,'p'=>$p,'v'=>$v]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function saveVersion(string $o,array $v):void{$s=$this->db->prepare("INSERT INTO diagnostic_pack_versions(organization_id,pack_id,methodology_version,schema_version,status,description,created_by,based_on_version,content_hash,published_at,created_at,updated_at) VALUES(:o,:p,:v,:sv,:st,:d,:u,:b,:h,:pa,NOW(6),NOW(6)) ON DUPLICATE KEY UPDATE status=VALUES(status),description=VALUES(description),content_hash=VALUES(content_hash),published_at=VALUES(published_at),updated_at=NOW(6)");$s->execute(['o'=>$o,'p'=>$v['pack_id'],'v'=>$v['methodology_version'],'sv'=>$v['schema_version'],'st'=>$v['status'],'d'=>$v['description']??'','u'=>$v['created_by'],'b'=>$v['based_on_version']??null,'h'=>$v['content_hash']??str_repeat('0',64),'pa'=>$v['published_at']??null]);}
 public function publishCompiled(string $o,array $p,int $rv,string $json,string $hash):void{$s=$this->db->prepare("INSERT INTO diagnostic_packs(organization_id,pack_id,version,name,target_domain,status,methodology_json,content_hash,lock_version,published_at,active_version,active_methodology_version) VALUES(:o,:p,:v,:n,:d,'published',CAST(:j AS JSON),:h,0,NOW(6),:v,:mv) ON DUPLICATE KEY UPDATE name=VALUES(name),target_domain=VALUES(target_domain),status='published',methodology_json=VALUES(methodology_json),content_hash=VALUES(content_hash),published_at=NOW(6),active_version=VALUES(active_version),active_methodology_version=VALUES(active_methodology_version)");$s->execute(['o'=>$o,'p'=>$p['pack_id'],'v'=>$rv,'n'=>$p['name'],'d'=>$p['domain'],'j'=>$json,'h'=>$hash,'mv'=>$p['methodology_version']]);}
 public function entities(string $o,string $p,string $v):array{$s=$this->db->prepare('SELECT entity_type,entity_id,position,enabled,payload_json FROM diagnostic_methodology_entities WHERE organization_id=:o AND pack_id=:p AND methodology_version=:v ORDER BY entity_type,position,entity_id');$s->execute(['o'=>$o,'p'=>$p,'v'=>$v]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$r)$r['payload']=json_decode($r['payload_json'],true,512,JSON_THROW_ON_ERROR);return $rows;}
 public function saveEntity(string $o,string $p,string $v,string $t,string $id,array $payload,int $position,bool $enabled):void{$s=$this->db->prepare('INSERT INTO diagnostic_methodology_entities(organization_id,pack_id,methodology_version,entity_type,entity_id,position,enabled,payload_json,updated_at) VALUES(:o,:p,:v,:t,:id,:pos,:en,:json,NOW(6)) ON DUPLICATE KEY UPDATE position=VALUES(position),enabled=VALUES(enabled),payload_json=VALUES(payload_json),updated_at=NOW(6)');$s->execute(['o'=>$o,'p'=>$p,'v'=>$v,'t'=>$t,'id'=>$id,'pos'=>$position,'en'=>$enabled?1:0,'json'=>json_encode($payload,JSON_THROW_ON_ERROR)]);}
 public function entity(string $o,string $p,string $v,string $t,string $id):?array{foreach($this->entities($o,$p,$v) as $row)if($row['entity_type']===$t&&$row['entity_id']===$id)return $row;return null;}
 public function deleteEntity(string $o,string $p,string $v,string $t,string $id):void{$s=$this->db->prepare('DELETE FROM diagnostic_methodology_entities WHERE organization_id=:o AND pack_id=:p AND methodology_version=:v AND entity_type=:t AND entity_id=:id');$s->execute(['o'=>$o,'p'=>$p,'v'=>$v,'t'=>$t,'id'=>$id]);}
 public function scenarios(string $o,string $p,string $v):array{$s=$this->db->prepare('SELECT scenario_id,name,input_json,expected_json FROM diagnostic_test_scenarios WHERE organization_id=:o AND pack_id=:p AND methodology_version=:v');$s->execute(['o'=>$o,'p'=>$p,'v'=>$v]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$r){$r['input']=json_decode($r['input_json'],true);$r['expected']=json_decode($r['expected_json'],true);}return $rows;}
 public function saveScenario(string $o,string $p,string $v,array $x):void{$s=$this->db->prepare('INSERT INTO diagnostic_test_scenarios VALUES(:o,:p,:v,:id,:n,:i,:e,NOW(6)) ON DUPLICATE KEY UPDATE name=VALUES(name),input_json=VALUES(input_json),expected_json=VALUES(expected_json)');$s->execute(['o'=>$o,'p'=>$p,'v'=>$v,'id'=>$x['id'],'n'=>$x['name'],'i'=>json_encode($x['input'],JSON_THROW_ON_ERROR),'e'=>json_encode($x['expected'],JSON_THROW_ON_ERROR)]);}
 public function deleteScenario(string $o,string $p,string $v,string $id):void{$s=$this->db->prepare('DELETE FROM diagnostic_test_scenarios WHERE organization_id=:o AND pack_id=:p AND methodology_version=:v AND scenario_id=:id');$s->execute(['o'=>$o,'p'=>$p,'v'=>$v,'id'=>$id]);}
 public function saveTestResult(string $o,array $r):void{$s=$this->db->prepare('INSERT INTO diagnostic_test_results VALUES(:o,:run,:p,:v,:scenario,:status,:result,NOW(6))');$s->execute(['o'=>$o,'run'=>$r['run_id'],'p'=>$r['pack_id'],'v'=>$r['version'],'scenario'=>$r['scenario_id'],'status'=>$r['status'],'result'=>json_encode($r['result'],JSON_THROW_ON_ERROR)]);}
 public function audit(string $o,array $e):void{$s=$this->db->prepare('INSERT INTO diagnostic_methodology_audit VALUES(:o,:id,:p,:v,:u,:t,:entity,:old,:new,NOW(6))');$s->execute(['o'=>$o,'id'=>$e['id'],'p'=>$e['pack_id'],'v'=>$e['version'],'u'=>$e['user_id'],'t'=>$e['entity_type'],'entity'=>$e['entity_id'],'old'=>isset($e['old'])?json_encode($e['old'],JSON_THROW_ON_ERROR):null,'new'=>isset($e['new'])?json_encode($e['new'],JSON_THROW_ON_ERROR):null]);}
 public function auditHistory(string $o,string $p='',string $v='',int $limit=100):array{$sql='SELECT audit_id,pack_id,methodology_version,user_id,entity_type,entity_id,old_value_json,new_value_json,created_at FROM diagnostic_methodology_audit WHERE organization_id=:o';$args=['o'=>$o];if($p!==''){$sql.=' AND pack_id=:p';$args['p']=$p;}if($v!==''){$sql.=' AND methodology_version=:v';$args['v']=$v;}$sql.=' ORDER BY created_at DESC LIMIT '.max(1,min(500,$limit));$s=$this->db->prepare($sql);$s->execute($args);$rows=$s->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$row){$row['old_value']=$row['old_value_json']===null?null:json_decode($row['old_value_json'],true);$row['new_value']=$row['new_value_json']===null?null:json_decode($row['new_value_json'],true);unset($row['old_value_json'],$row['new_value_json']);}return $rows;}
 public function diagnosticRuns(string $o,int $limit=100):array
 {
  $sql='SELECT session.session_id,session.pack_id,COALESCE(session.methodology_version,CAST(session.pack_version AS CHAR)) methodology_version,session.schema_version,session.target_domain,session.target_subject_type,session.target_subject_id,session.status,session.started_at,session.completed_at,(SELECT COUNT(*) FROM diagnostic_interview_turns turn_row WHERE turn_row.organization_id=session.organization_id AND turn_row.diagnostic_id=session.session_id) interview_turns,(SELECT COUNT(*) FROM diagnostic_records record_row WHERE record_row.organization_id=session.organization_id AND record_row.session_id=session.session_id AND record_row.record_type="finding") findings,(SELECT COUNT(*) FROM diagnostic_records critical_row WHERE critical_row.organization_id=session.organization_id AND critical_row.session_id=session.session_id AND critical_row.record_type="finding" AND JSON_UNQUOTE(JSON_EXTRACT(critical_row.value_json,"$.severity")) IN ("critical","high")) critical_findings FROM diagnostic_sessions session WHERE session.organization_id=:o ORDER BY COALESCE(session.started_at,session.created_at) DESC LIMIT '.max(1,min(500,$limit));
  $s=$this->db->prepare($sql);$s->execute(['o'=>$o]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);
  $coverage=$this->db->prepare('SELECT statement FROM diagnostic_records WHERE organization_id=:o AND session_id=:s AND record_type="assessment"');
  foreach($rows as &$row){$coverage->execute(['o'=>$o,'s'=>$row['session_id']]);$values=[];foreach($coverage->fetchAll(PDO::FETCH_COLUMN) as $statement)if(preg_match_all('/coverage\s+([0-9]+(?:\.[0-9]+)?)/i',(string)$statement,$matches))foreach($matches[1] as $value)$values[]=(float)$value;$row['coverage']=$values===[]?null:round(array_sum($values)/count($values)*100,1);}
  return $rows;
 }
}
