<?php
declare(strict_types=1);

namespace App\Engineering\Domain\DomainDevelopment;

enum EngineeringDomainArtifactType: string
{
    case DOMAIN_SPECIFICATION = 'DOMAIN_SPECIFICATION';
    case DOMAIN_ACCEPTANCE_CRITERIA = 'DOMAIN_ACCEPTANCE_CRITERIA';
    case CAPABILITY_MAP = 'CAPABILITY_MAP';
    case CAPABILITY_SPECIFICATION = 'CAPABILITY_SPECIFICATION';
    case FEATURE_CONTEXT_PACK = 'FEATURE_CONTEXT_PACK';
    case FEATURE_DEPENDENCY_GRAPH = 'FEATURE_DEPENDENCY_GRAPH';
    case CONTRACT_REGISTRY = 'CONTRACT_REGISTRY';
    case DOMAIN_EVENT_REGISTRY = 'DOMAIN_EVENT_REGISTRY';
    case DOMAIN_QA_PLAN = 'DOMAIN_QA_PLAN';
    case DOMAIN_ARCHITECTURE = 'DOMAIN_ARCHITECTURE';
    case DOMAIN_ARCHITECTURE_CONSTITUTION = 'DOMAIN_ARCHITECTURE_CONSTITUTION';
    case DOMAIN_DECOMPOSITION = 'DOMAIN_DECOMPOSITION';
    case MIGRATION_PLAN = 'MIGRATION_PLAN';
    case INTEGRATION_STRATEGY = 'INTEGRATION_STRATEGY';
    case DOMAIN_QA_REPORT = 'DOMAIN_QA_REPORT';
    case DOMAIN_INTEGRATION_RELEASE_REPORT = 'DOMAIN_INTEGRATION_RELEASE_REPORT';
    case DOMAIN_RELEASE_MANIFEST = 'DOMAIN_RELEASE_MANIFEST';
}
