<?php
declare(strict_types=1);
namespace Domains\Diagnostic\Application\Service;
use DateTimeImmutable;
use DomainException;
use Domains\Diagnostic\Application\Contract\MethodologyStudioRepositoryInterface;
use Domains\Diagnostic\Methodology\{CompiledDiagnosticPack,PackCompiler};
use Domains\Diagnostic\Methodology\Engine\{MethodologyEngine,MetricExpressionEngine};
use Domains\Diagnostic\Methodology\Input\{DiagnosticInput,EvidenceSignal,ObservedValue};
use Domains\Diagnostic\Methodology\Serialization\MethodologyPackSerializer;
use Domains\Diagnostic\Methodology\Loader\PackLoader;
use Domains\Diagnostic\Methodology\Validation\PackValidator;
final readonly class MethodologyStudioService
{
 private const MAP=['AREA'=>'sections','CRITERION'=>'criteria','FACT'=>'facts','METRIC'=>'metrics','QUESTION'=>'questions','EVIDENCE_REQUIREMENT'=>'evidence_requirements','RULE'=>'rules','DEPENDENCY'=>'dependencies','RECOMMENDATION'=>'recommendations','BENCHMARK'=>'benchmarks','SCORING'=>'scoring'];
 public function __construct(private MethodologyStudioRepositoryInterface $repository,private PackCompiler $compiler=new PackCompiler(),private MethodologyEngine $engine=new MethodologyEngine()){}
 public function packs(string $o):array{return $this->repository->packs($o);}public function pack(string $o,string $p):array{return $this->repository->pack($o,$p)??throw new DomainException('Pack not found.');}public function versions(string $o,string $p):array{return $this->repository->versions($o,$p);}
 public function entities(string $o,string $p,string $v):array{return $this->repository->entities($o,$p,$v);}
 public function scenarios(string $o,string $p,string $v):array{return $this->repository->scenarios($o,$p,$v);}
 public function history(string $o,string $p='',string $v=''):array{return $this->repository->auditHistory($o,$p,$v);}public function runs(string $o):array{return $this->repository->diagnosticRuns($o);}
 public function saveScenario(string $o,string $p,string $v,array $scenario,string $user):void{$this->requiredDraft($o,$p,$v);$this->repository->saveScenario($o,$p,$v,$scenario);$this->repository->audit($o,['id'=>bin2hex(random_bytes(16)),'pack_id'=>$p,'version'=>$v,'user_id'=>$user,'entity_type'=>'SCENARIO','entity_id'=>$scenario['id'],'new'=>$scenario]);}
 public function create(string $o,array $input,string $user):array{$id=strtolower(trim((string)($input['slug']??'')));if(!preg_match('/^[a-z][a-z0-9-]+$/',$id))throw new DomainException('Invalid pack slug.');$v=(string)($input['methodology_version']??'0.1.0');$this->assertSemver($v);if(trim((string)($input['name']??''))===''||trim((string)($input['domain']??''))==='')throw new DomainException('Pack name and domain are required.');$this->repository->savePack($o,['id'=>$id,'name'=>(string)$input['name'],'domain'=>(string)$input['domain']]);$row=['pack_id'=>$id,'methodology_version'=>$v,'schema_version'=>'diagnostic-pack-schema:1','status'=>'DRAFT','description'=>(string)($input['description']??''),'created_by'=>$user];$this->repository->saveVersion($o,$row);$this->repository->audit($o,['id'=>bin2hex(random_bytes(16)),'pack_id'=>$id,'version'=>$v,'user_id'=>$user,'entity_type'=>'PACK','entity_id'=>$id,'new'=>$row]);return $row;}
 public function saveEntity(string $o,string $p,string $v,string $type,array $payload,string $user):void{$this->requiredDraft($o,$p,$v);$type=strtoupper($type);if(!isset(self::MAP[$type]))throw new DomainException('Unsupported methodology entity type.');$id=(string)($payload['id']??'');if($id===''&&$type==='DEPENDENCY')$id=(string)($payload['source']??'').'--'.(string)($payload['target']??'');if($id===''&&$type==='SCORING')$id=(string)($payload['criterion']??'').'--'.(string)($payload['metric']??'');if(!preg_match('/^[a-z][a-z0-9_.-]+$/',$id))throw new DomainException('Stable lowercase entity id is required.');$payload['id']=$id;$old=$this->repository->entity($o,$p,$v,$type,$id);$this->repository->saveEntity($o,$p,$v,$type,$id,$payload,(int)($payload['order']??0),(bool)($payload['enabled']??true));$this->repository->audit($o,['id'=>bin2hex(random_bytes(16)),'pack_id'=>$p,'version'=>$v,'user_id'=>$user,'entity_type'=>$type,'entity_id'=>$id,'old'=>$old['payload']??null,'new'=>$payload]);}
 public function deleteEntity(string $o,string $p,string $v,string $type,string $id,string $user):void{$this->requiredDraft($o,$p,$v);$type=strtoupper($type);$old=$this->repository->entity($o,$p,$v,$type,$id)??throw new DomainException('Entity not found.');$this->repository->deleteEntity($o,$p,$v,$type,$id);$this->repository->audit($o,['id'=>bin2hex(random_bytes(16)),'pack_id'=>$p,'version'=>$v,'user_id'=>$user,'entity_type'=>$type,'entity_id'=>$id,'old'=>$old['payload'],'new'=>null]);}
 public function compile(string $o,string $p,string $v):CompiledDiagnosticPack{return $this->compiler->compile($this->document($o,$p,$v));}
 public function validate(string $o,string $p,string $v):array{$row=$this->requiredDraft($o,$p,$v);$this->repository->saveVersion($o,array_merge($row,['status'=>'VALIDATING']));try{$pack=(new PackLoader())->load($this->document($o,$p,$v));$validation=(new PackValidator())->validate($pack);$format=fn($issue)=>['code'=>$issue->code,'path'=>$issue->path,'message'=>$issue->message];$errors=array_map($format,$validation->errors);$warnings=array_map($format,$validation->warnings);if(!$validation->isValid()){$this->repository->saveVersion($o,array_merge($row,['status'=>'DRAFT']));return ['valid'=>false,'status'=>'DRAFT','errors'=>$errors,'warnings'=>$warnings];}$this->repository->saveVersion($o,array_merge($row,['status'=>'READY','content_hash'=>(new MethodologyPackSerializer())->hash($pack)]));return ['valid'=>true,'status'=>'READY','errors'=>[],'warnings'=>$warnings];}catch(\Throwable $e){$this->repository->saveVersion($o,array_merge($row,['status'=>'DRAFT']));return ['valid'=>false,'status'=>'DRAFT','errors'=>[['code'=>'pack.load_failed','path'=>'pack','message'=>$e->getMessage()]],'warnings'=>[]];}}
 public function simulate(string $o,string $p,string $v,array $input):array{$pack=$this->compile($o,$p,$v);$now=new DateTimeImmutable();$e=new EvidenceSignal('simulator','MANUAL',.9,1,$now);$facts=[];$metrics=[];$rawFacts=is_array($input['facts']??null)?$input['facts']:[];$rawMetrics=is_array($input['metrics']??null)?$input['metrics']:[];foreach($rawFacts as $id=>$value)$facts[$id]=new ObservedValue($value,[$e]);foreach($rawMetrics as $id=>$value)$metrics[$id]=new ObservedValue($value,[$e]);$values=$rawFacts+$rawMetrics;$expressions=new MetricExpressionEngine();$pending=array_filter($pack->pack->metrics,fn($metric)=>$metric->formula!==null&&!isset($metrics[$metric->id]));for($pass=0;$pass<count($pending)+1&&$pending!==[];$pass++){foreach($pending as $key=>$metric){try{$value=$expressions->evaluate((string)$metric->formula,$values);$metrics[$metric->id]=new ObservedValue($value,[$e]);$values[$metric->id]=$value;unset($pending[$key]);}catch(\InvalidArgumentException $exception){if(!str_contains($exception->getMessage(),'input is missing'))throw $exception;}}}if($pending!==[])throw new DomainException('Unable to resolve metric formulas: '.implode(', ',array_map(fn($metric)=>$metric->id,$pending)));$r=$this->engine->evaluate(new DiagnosticInput($facts,$metrics,$now),$pack->pack);$findingIds=array_map(fn($f)=>$f->ruleId,$r->findings);$recommendations=[];foreach($pack->recommendationsById as $x)if(array_intersect($x->triggerRules,$findingIds))$recommendations[]=$x->id;return ['score'=>$r->score,'coverage'=>$r->coverage->ratio,'confidence'=>$r->confidence,'area_scores'=>$r->sectionScores,'assessments'=>$r->assessments,'findings'=>$r->findings,'dependencies'=>$r->dependencies,'recommendations'=>$recommendations,'derived_metrics'=>array_map(fn($value)=>$value->value,array_diff_key($metrics,$rawMetrics))];}
 public function runRegression(string $o,string $p,string $v):array{$run=bin2hex(random_bytes(16));$summary=['passed'=>0,'changed'=>0,'failed'=>0,'results'=>[]];foreach($this->repository->scenarios($o,$p,$v) as $scenario){try{$actual=$this->simulate($o,$p,$v,$scenario['input']);$expected=$scenario['expected'];$actualFindings=array_map(fn($f)=>$f->ruleId,$actual['findings']);$missing=array_values(array_diff($expected['findings']??[],$actualFindings));$unexpected=array_values(array_diff($actualFindings,$expected['findings']??$actualFindings));$missingRecommendations=array_values(array_diff($expected['recommendations']??[],$actual['recommendations']));$scoreOk=!isset($expected['score_min'])||$actual['score'] >= (float)$expected['score_min'];$status=$missing===[]&&$missingRecommendations===[]&&$scoreOk?($unexpected===[]?'PASSED':'CHANGED'):'FAILED';$details=['missing_findings'=>$missing,'unexpected_findings'=>$unexpected,'missing_recommendations'=>$missingRecommendations,'score'=>$actual['score']];}catch(\Throwable $e){$status='FAILED';$details=['error'=>$e->getMessage()];}$summary[strtolower($status)]++;$summary['results'][]=['scenario_id'=>$scenario['scenario_id'],'name'=>$scenario['name'],'status'=>$status,'details'=>$details];$this->repository->saveTestResult($o,['run_id'=>$run,'pack_id'=>$p,'version'=>$v,'scenario_id'=>$scenario['scenario_id'],'status'=>$status,'result'=>$details]);}return $summary;}
 public function publish(string $o,string $p,string $v,string $user):void{$validation=$this->validate($o,$p,$v);if(!$validation['valid'])throw new DomainException('Pack validation failed.');if($this->repository->scenarios($o,$p,$v)===[])throw new DomainException('At least one passing simulation scenario is required.');$regression=$this->runRegression($o,$p,$v);if($regression['failed']>0||$regression['changed']>0||$regression['passed']<1)throw new DomainException('Publish requires at least one PASSED scenario and no FAILED or CHANGED scenarios.');$row=$this->repository->version($o,$p,$v)??throw new DomainException('Pack version not found.');$packRow=$this->pack($o,$p);$compiled=$this->compile($o,$p,$v);$serializer=new MethodologyPackSerializer();$hash=$serializer->hash($compiled->pack);$runtime=$this->runtimeVersion($v);$this->repository->publishCompiled($o,['pack_id'=>$p,'name'=>$packRow['name'],'domain'=>$packRow['domain'],'methodology_version'=>$v],$runtime,$serializer->encode($compiled->pack),$hash);$this->repository->saveVersion($o,array_merge($row,['status'=>'PUBLISHED','published_at'=>(new DateTimeImmutable())->format('Y-m-d H:i:s.u'),'content_hash'=>$hash]));$this->repository->activate($o,$p,$v,$runtime);$this->repository->audit($o,['id'=>bin2hex(random_bytes(16)),'pack_id'=>$p,'version'=>$v,'user_id'=>$user,'entity_type'=>'VERSION','entity_id'=>$v,'old'=>['status'=>'READY'],'new'=>['status'=>'PUBLISHED','active'=>true]]);}
 public function archive(string $o,string $p,string $v,string $user):void{$row=$this->repository->version($o,$p,$v)??throw new DomainException('Pack version not found.');if($row['status']!=='PUBLISHED')throw new DomainException('Only a published version can be archived.');$this->repository->saveVersion($o,array_merge($row,['status'=>'ARCHIVED']));$this->repository->audit($o,['id'=>bin2hex(random_bytes(16)),'pack_id'=>$p,'version'=>$v,'user_id'=>$user,'entity_type'=>'VERSION','entity_id'=>$v,'old'=>['status'=>'PUBLISHED'],'new'=>['status'=>'ARCHIVED']]);}
 public function activate(string $o,string $p,string $v,string $user):void{$row=$this->repository->version($o,$p,$v)??throw new DomainException('Pack version not found.');if($row['status']!=='PUBLISHED')throw new DomainException('Only a published version can be activated.');$this->repository->activate($o,$p,$v,$this->runtimeVersion($v));$this->repository->audit($o,['id'=>bin2hex(random_bytes(16)),'pack_id'=>$p,'version'=>$v,'user_id'=>$user,'entity_type'=>'VERSION','entity_id'=>$v,'new'=>['active'=>true]]);}
 public function clone(string $o,string $p,string $from,string $to,string $user):void{$this->assertSemver($to);$source=$this->repository->version($o,$p,$from)??throw new DomainException('Source version not found.');if($this->repository->version($o,$p,$to)!==null)throw new DomainException('Target methodology version already exists.');$this->repository->saveVersion($o,array_merge($source,['methodology_version'=>$to,'status'=>'DRAFT','created_by'=>$user,'based_on_version'=>$from,'published_at'=>null]));foreach($this->repository->entities($o,$p,$from) as $e)$this->repository->saveEntity($o,$p,$to,$e['entity_type'],$e['entity_id'],$e['payload'],(int)$e['position'],(bool)$e['enabled']);$this->repository->audit($o,['id'=>bin2hex(random_bytes(16)),'pack_id'=>$p,'version'=>$to,'user_id'=>$user,'entity_type'=>'VERSION','entity_id'=>$to,'new'=>['status'=>'DRAFT','based_on_version'=>$from]]);}
 private function document(string $o,string $p,string $v):array{$this->repository->version($o,$p,$v)??throw new DomainException('Pack version not found.');$pack=$this->pack($o,$p);$doc=['id'=>$p,'version'=>$this->runtimeVersion($v),'name'=>$pack['name'],'sections'=>[],'criteria'=>[],'facts'=>[],'metrics'=>[],'questions'=>[],'evidence_requirements'=>[],'rules'=>[],'dependencies'=>[],'recommendations'=>[],'benchmarks'=>[],'scoring'=>[]];foreach($this->repository->entities($o,$p,$v) as $e)if($e['enabled'])$doc[self::MAP[$e['entity_type']]][]=$e['payload'];return $doc;}
 private function requiredDraft(string $o,string $p,string $v):array{$row=$this->repository->version($o,$p,$v)??throw new DomainException('Pack version not found.');if(!in_array($row['status'],['DRAFT','VALIDATING','READY'],true))throw new DomainException('Published or archived versions are immutable.');return $row;}
 private function runtimeVersion(string $v):int{if(!preg_match('/^(\d+)\.(\d+)\.(\d+)$/',$v,$m))throw new DomainException('Methodology version must use SemVer (for example 0.2.0).');return max(1,((int)$m[1]*1000000)+((int)$m[2]*1000)+(int)$m[3]);}
 private function assertSemver(string $v):void{$this->runtimeVersion($v);}
}
