<?php
declare(strict_types=1);
use Domains\Diagnostic\AI\PromptRegistry;
use Domains\Diagnostic\Evaluation\{CostEvaluator,DiagnosticComparisonService,EvaluationMetrics,ReDiagnosticSchedule,RegressionComparator};
use Domains\Diagnostic\Infrastructure\AI\{FakeAiGateway,RecordedAiGateway,RetryingAiGateway};
use Domains\Diagnostic\Interview\{ContradictionDetectionService,DiagnosticMode,ExtractedFact,FactExtractionService,HypothesisGenerationService,InterviewCoordinator,NextBestQuestionEngine,RootCauseAnalysisService};
use Domains\Diagnostic\Methodology\PackCompiler;
use Domains\Diagnostic\Model\{DiagnosticState,Fact,FactStatus,HypothesisStatus};
use Domains\Diagnostic\Report\{DiagnosticReportBuilder,ExplainabilityGraph,PriorityEngine,RecommendationGenerationService,RecommendationStatus,RoadmapBuilder};
use Kernel\Action\{Action,ActionStatus,ExecutionResult};
use Kernel\Action\Contract\ActionRepositoryInterface;
use Kernel\Action\Service\{ActionExecutor,ActionService};
use Domains\Diagnostic\Application\UseCase\AcceptDiagnosticRecommendation;
require dirname(__DIR__,2).'/vendor/autoload.php';
function p46(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
function state(string $id,array $missing,array $findings=[],array $recommendations=[],float $score=50):DiagnosticState{return new DiagnosticState($id,'sales',1,1,new DateTimeImmutable(),[],$missing,[],[] ,[],$findings,[],[],$recommendations,[],['pack'=>.8],.8,['pack'=>$score,'sections'=>['pipeline'=>$score]],[],[],[]);}
$root=dirname(__DIR__,2);$pack=(new PackCompiler())->compile($root.'/resources/diagnostic/sales/0.1.0/sales-diagnostic-pack.json');
p46(count((new PromptRegistry())->versions())===7,'Prompt registry incomplete.');
$decision=(new NextBestQuestionEngine())->decide(state('d1',['sales_fact_01','sales_fact_02']),$pack,[],DiagnosticMode::DeepDiagnostic,5,30);p46($decision!==null&&$decision->targetFacts!==[],'Adaptive question selection failed.');
$output=['facts'=>[['key'=>'sales_fact_01','value'=>true,'provenance'=>'REPORTED','confidence'=>.7,'evidence_ids'=>['ev1']]],'metrics'=>[],'evidence'=>[['id'=>'ev1','title'=>'Interview','value'=>'yes']],'uncertainties'=>[],'contradictions'=>[],'missing_information'=>[]];$recorded=new RecordedAiGateway(new FakeAiGateway([$output]));$extracted=(new FactExtractionService($recorded))->extract('org','d1',$decision->question,'yes',$pack);p46(count($extracted->candidateFacts)===1&&count($recorded->calls)===1,'Structured extraction/audit failed.');
$turn=(new InterviewCoordinator(new FactExtractionService(new FakeAiGateway([$output]))))->processAnswer('org',state('d1',['sales_fact_01']),$pack,$decision,'yes',[],[],DiagnosticMode::DeepDiagnostic,[],5,30);p46($turn->state->revision===2&&isset($turn->state->knownFacts['sales_fact_01']),'Interview coordinator did not rebuild state.');
$retry=(new RetryingAiGateway(new FakeAiGateway([new RuntimeException('transient'),$output])));$retried=(new FactExtractionService($retry))->extract('org','d1','q','a',$pack);p46(count($retried->candidateFacts)===1,'AI retry policy failed.');
$hallucinated=$output;$hallucinated['facts'][0]['key']='invented_fact';try{(new FactExtractionService(new FakeAiGateway([$hallucinated])))->extract('org','d1','q','a',$pack);throw new RuntimeException('Hallucinated fact entered domain.');}catch(UnexpectedValueException){}
$now=new DateTimeImmutable();$existing=new Fact('f','d1','sales_fact_01',true,'boolean',FactStatus::Known,.9,'CRM',['crm'],$now,$now);$contradictions=(new ContradictionDetectionService())->detect([$existing],[new ExtractedFact('sales_fact_01',false,'boolean','REPORTED',.8,['interview'])]);p46(count($contradictions)===1&&$contradictions[0]->status==='OPEN','Contradiction was not retained.');
$hypOut=['hypotheses'=>[['hypothesis'=>'Routing is inconsistent','supporting_evidence'=>['crm','interview'],'contradicting_evidence'=>[],'required_evidence'=>[],'confidence_estimate'=>.99]]];$hyp=(new HypothesisGenerationService(new FakeAiGateway([$hypOut])))->generate('org','d1',['finding'],['crm','interview'])[0];p46($hyp->confidence===.69,'AI confidence was accepted as final.');$supported=$hyp->transition(HypothesisStatus::Supported,.85);$causes=(new RootCauseAnalysisService())->analyze([$supported],['finding-1'],.9);p46(count($causes)===1,'Root-cause evidence threshold failed.');
$priority=new PriorityEngine();$score=$priority->score(.9,.9,.8,.2,.2,.2,.1);p46($score>45,'Priority normalization failed.');$templates=[['id'=>'rec-1','finding_ids'=>['finding-1'],'rationale'=>'Restore routing ownership.','actions'=>['Assign routing owner','Monitor SLA'],'success_metrics'=>['lead_response_time'],'expected_impact'=>'Higher contact rate','effort'=>'low','priority_inputs'=>['impact'=>.9,'confidence'=>.9,'urgency'=>.8,'effort'=>.2,'cost'=>.2,'time'=>.2,'risk'=>.1]]];$recommendations=(new RecommendationGenerationService())->generate($templates,['finding-1'],array_map(fn($x)=>$x->id,$causes));p46(count($recommendations)===1&&$recommendations[0]->priorityScore>0,'Recommendation generation failed.');
$graph=new ExplainabilityGraph();foreach([['e','EVIDENCE',[]],['f','FACT',['e']],['m','METRIC',['f']],['a','ASSESSMENT',['m']],['finding-1','FINDING',['a']],[$causes[0]->id,'ROOT_CAUSE',['finding-1']],['rec-1','RECOMMENDATION',[$causes[0]->id]]] as [$id,$type,$up])$graph->add($id,$type,[],$up);p46(count($graph->explain('rec-1')['trace'])===7,'Explainability trace incomplete.');
$report=(new DiagnosticReportBuilder())->build(state('d1',[],[], $recommendations,62),[],'Validated summary');p46(json_encode($report,JSON_THROW_ON_ERROR)!==''&&count($report->roadmap)===2,'Structured report/roadmap failed.');
$repo=new class implements ActionRepositoryInterface{public array $items=[];public function save(Action $a):Action{$this->items[$a->id]=$a;return $a;}public function find(string $o,string $id):?Action{return $this->items[$id]??null;}public function existsByIdempotencyKey(string $o,string $k):bool{return false;}public function transition(string $o,string $id,ActionStatus $f,ActionStatus $t):bool{return false;}public function claim(string $o,string $id,string $w):?Action{return null;}public function claimNext(string $w):?Action{return null;}public function finish(Action $a,ExecutionResult $r):void{}public function requeueStale(int $s):int{return 0;}};$action=(new AcceptDiagnosticRecommendation(new ActionService($repo,new ActionExecutor([]))))->execute('org','d1',$recommendations[0]);p46($recommendations[0]->status===RecommendationStatus::Accepted&&$action->status===ActionStatus::PendingApproval,'COS Action integration failed.');
$metrics=(new EvaluationMetrics())->classification(['a','b'],['a','c'],['a','b','c','d']);p46($metrics->precision===.5&&$metrics->recall===.5&&$metrics->hallucinationRate===.5,'Evaluation metrics failed.');$cost=(new CostEvaluator())->evaluate($recorded->calls,1,1,1);p46($cost->calls===1&&$cost->cost>0,'Cost evaluation failed.');p46(!(new RegressionComparator())->compare(['accuracy'=>.9,'hallucination_rate'=>.1],['accuracy'=>.8,'hallucination_rate'=>.2])['promotable'],'Regression gate failed.');$schedule=new ReDiagnosticSchedule('d1',new DateTimeImmutable('2026-09-05'),30);p46($schedule->dueAt->format('Y-m-d')==='2026-10-05','Re-diagnostic schedule failed.');$comparison=(new DiagnosticComparisonService())->compare(state('d1',[],[],[],50),state('d2',[],[],[],65));p46($comparison->outcome==='IMPROVED','Before/after comparison failed.');
$dataset=json_decode(file_get_contents($root.'/tests/fixtures/diagnostic/evaluation/sales-v0.1.json'),true,512,JSON_THROW_ON_ERROR);p46(count($dataset['cases'])===30,'Synthetic dataset requires 30 cases.');
echo "Diagnostic Phase 4-6 closed-loop contract passed.\n";
