<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);$read=static fn(string $p):string=>is_file($root.'/'.$p)?(string)file_get_contents($root.'/'.$p):throw new RuntimeException('Missing: '.$p);
$t=$read('docs/03-architecture/wave13-migration-tracker.md');foreach(['VR-027','VR-028','VR-029','VR-030','VR-031','VR-032'] as $id)if(preg_match('/\\| '.preg_quote($id,'/').' \\|[^\\n]*\\| DONE \\|/',$t)!==1)throw new RuntimeException('Not DONE: '.$id);
foreach(['symfony/templates/experience/public/property_catalog.html.twig','symfony/templates/experience/public/property_detail.html.twig','symfony/templates/experience/public/property_presentation.html.twig','symfony/templates/experience/public/property_seo.html.twig','symfony/templates/experience/public/property_favourites.html.twig','symfony/templates/experience/public/property_submit.html.twig'] as $p){$s=$read($p);foreach(['tn-','style=','onclick='] as $x)if(str_contains($s,$x))throw new RuntimeException($p.' restored '.$x);}
if(is_file($root.'/app/Interfaces/Web/View/property/presentation.phtml'))throw new RuntimeException('Legacy presentation PHTML restored.');$read('app/Interfaces/Web/View/property/pdf.phtml');
$p=$read('symfony/src/Web/Property/PropertyPageController.php');foreach(['QueryBusInterface','CommandBusInterface','GetPublicPropertyPresentationQuery','ReceivePublicLeadCommand'] as $m)if(!str_contains($p,$m))throw new RuntimeException('Presentation boundary missing '.$m);if(str_contains($p,'PhtmlRenderer'))throw new RuntimeException('PHTML restored.');
$s=$read('symfony/src/Web/Property/PublicPropertySubmitController.php');foreach(['CommandBusInterface','SubmitPublicPropertyCommand','HTTP_CREATED'] as $m)if(!str_contains($s,$m))throw new RuntimeException('Public intake missing '.$m);if(str_contains($s,'INTAKE_UNAVAILABLE'))throw new RuntimeException('Intake placeholder restored.');
echo "Public Property canonical family complete.\n";
