CREATE TABLE IF NOT EXISTS cos_agent_runs (
    id VARCHAR(40) NOT NULL,
    organization_id VARCHAR(40) NOT NULL,
    agent_name VARCHAR(160) NOT NULL,
    agent_version VARCHAR(40) NOT NULL,
    provider VARCHAR(80) NOT NULL,
    model VARCHAR(120) NOT NULL,
    prompt_version VARCHAR(40) NOT NULL,
    schema_version VARCHAR(40) NOT NULL,
    subject_type VARCHAR(100) NULL,
    subject_id VARCHAR(100) NULL,
    status ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'INVALID_OUTPUT') NOT NULL,
    context_reference JSON NULL,
    input_snapshot JSON NULL,
    output JSON NULL,
    confidence DECIMAL(5, 4) NULL,
    input_tokens INT UNSIGNED NULL,
    output_tokens INT UNSIGNED NULL,
    cost_amount DECIMAL(14, 6) NULL,
    cost_currency CHAR(3) NULL,
    duration_ms INT UNSIGNED NULL,
    error TEXT NULL,
    correlation_id VARCHAR(40) NOT NULL,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_cos_agent_runs_org_agent (organization_id, agent_name, created_at),
    KEY idx_cos_agent_runs_subject (organization_id, subject_type, subject_id, created_at),
    KEY idx_cos_agent_runs_status (status, created_at),
    KEY idx_cos_agent_runs_correlation (organization_id, correlation_id),
    CONSTRAINT chk_cos_agent_runs_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cos_audit_log (
    id VARCHAR(40) NOT NULL,
    organization_id VARCHAR(40) NOT NULL,
    category VARCHAR(100) NOT NULL,
    actor_type ENUM('USER', 'AGENT', 'WORKER', 'INTEGRATION', 'SYSTEM') NOT NULL,
    actor_id VARCHAR(100) NOT NULL,
    subject_type VARCHAR(100) NOT NULL,
    subject_id VARCHAR(100) NOT NULL,
    action VARCHAR(160) NULL,
    reason TEXT NULL,
    input_references JSON NULL,
    changes JSON NULL,
    result JSON NULL,
    metadata JSON NULL,
    correlation_id VARCHAR(40) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_cos_audit_org_subject (organization_id, subject_type, subject_id, created_at),
    KEY idx_cos_audit_org_actor (organization_id, actor_type, actor_id, created_at),
    KEY idx_cos_audit_org_category (organization_id, category, created_at),
    KEY idx_cos_audit_correlation (organization_id, correlation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO tn_migrations (migration)
VALUES ('20260822_000011_cos_audit_agents');
