CREATE TABLE IF NOT EXISTS tn_spatial_scenes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id VARCHAR(40) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    title VARCHAR(220) NOT NULL,
    description TEXT NULL,
    scene_type ENUM('model', 'digital_twin', 'roomplan', 'panorama', 'gaussian_splat', 'mixed') NOT NULL DEFAULT 'model',
    viewer_type ENUM('threejs', 'external', 'panorama', 'gaussian_splat') NOT NULL DEFAULT 'threejs',
    provider ENUM('native', 'roomplan', 'polycam', 'matterport', 'canvas', 'scaniverse', 'blender', 'bim', 'other') NOT NULL DEFAULT 'native',
    status ENUM('draft', 'processing', 'review', 'published', 'failed', 'archived') NOT NULL DEFAULT 'draft',
    external_url VARCHAR(700) NULL,
    poster_media_id BIGINT UNSIGNED NULL,
    default_camera_json JSON NULL,
    settings_json JSON NULL,
    created_by_user_id BIGINT UNSIGNED NULL,
    published_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tn_spatial_scenes_public_id (public_id),
    UNIQUE KEY uq_tn_spatial_scenes_slug (slug),
    KEY idx_tn_spatial_scenes_public (status, scene_type, published_at),
    KEY idx_tn_spatial_scenes_author (created_by_user_id),
    CONSTRAINT fk_tn_spatial_scenes_poster FOREIGN KEY (poster_media_id) REFERENCES tn_media_assets (id) ON DELETE SET NULL,
    CONSTRAINT fk_tn_spatial_scenes_user FOREIGN KEY (created_by_user_id) REFERENCES tn_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tn_spatial_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scene_id BIGINT UNSIGNED NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    label VARCHAR(160) NULL,
    capture_method ENUM('lidar', 'roomplan', 'photogrammetry', 'bim', 'cad', 'manual', 'provider') NOT NULL DEFAULT 'manual',
    status ENUM('draft', 'processing', 'ready', 'failed', 'archived') NOT NULL DEFAULT 'draft',
    device_name VARCHAR(160) NULL,
    captured_at DATETIME NULL,
    notes TEXT NULL,
    metadata_json JSON NULL,
    created_by_user_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tn_spatial_versions_number (scene_id, version_number),
    KEY idx_tn_spatial_versions_scene (scene_id, status, created_at),
    CONSTRAINT fk_tn_spatial_versions_scene FOREIGN KEY (scene_id) REFERENCES tn_spatial_scenes (id) ON DELETE CASCADE,
    CONSTRAINT fk_tn_spatial_versions_user FOREIGN KEY (created_by_user_id) REFERENCES tn_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tn_spatial_captures (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id VARCHAR(40) NOT NULL,
    scene_id BIGINT UNSIGNED NOT NULL,
    version_id BIGINT UNSIGNED NULL,
    capture_type ENUM('lidar', 'roomplan', 'photogrammetry', 'bim', 'cad', 'manual', 'provider') NOT NULL DEFAULT 'manual',
    provider VARCHAR(80) NULL,
    external_id VARCHAR(190) NULL,
    device_name VARCHAR(160) NULL,
    status ENUM('uploading', 'received', 'processing', 'ready', 'failed', 'archived') NOT NULL DEFAULT 'received',
    source_payload JSON NULL,
    captured_by_user_id BIGINT UNSIGNED NULL,
    captured_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tn_spatial_captures_public_id (public_id),
    UNIQUE KEY uq_tn_spatial_captures_external (provider, external_id),
    KEY idx_tn_spatial_captures_scene (scene_id, status, created_at),
    CONSTRAINT fk_tn_spatial_captures_scene FOREIGN KEY (scene_id) REFERENCES tn_spatial_scenes (id) ON DELETE CASCADE,
    CONSTRAINT fk_tn_spatial_captures_version FOREIGN KEY (version_id) REFERENCES tn_spatial_versions (id) ON DELETE SET NULL,
    CONSTRAINT fk_tn_spatial_captures_user FOREIGN KEY (captured_by_user_id) REFERENCES tn_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tn_spatial_assets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id VARCHAR(40) NOT NULL,
    scene_id BIGINT UNSIGNED NOT NULL,
    version_id BIGINT UNSIGNED NULL,
    capture_id BIGINT UNSIGNED NULL,
    media_id BIGINT UNSIGNED NULL,
    asset_type ENUM('source', 'model_web', 'model_ar', 'texture', 'point_cloud', 'gaussian_splat', 'panorama', 'floorplan', 'poster', 'video', 'other') NOT NULL DEFAULT 'source',
    format VARCHAR(30) NOT NULL,
    storage ENUM('local', 'external') NOT NULL DEFAULT 'local',
    uri VARCHAR(700) NOT NULL,
    status ENUM('uploaded', 'queued', 'processing', 'ready', 'failed', 'archived') NOT NULL DEFAULT 'uploaded',
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT UNSIGNED NOT NULL DEFAULT 100,
    size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    checksum CHAR(64) NULL,
    metadata_json JSON NULL,
    error_message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tn_spatial_assets_public_id (public_id),
    KEY idx_tn_spatial_assets_scene (scene_id, status, asset_type, sort_order),
    KEY idx_tn_spatial_assets_version (version_id, status),
    CONSTRAINT fk_tn_spatial_assets_scene FOREIGN KEY (scene_id) REFERENCES tn_spatial_scenes (id) ON DELETE CASCADE,
    CONSTRAINT fk_tn_spatial_assets_version FOREIGN KEY (version_id) REFERENCES tn_spatial_versions (id) ON DELETE SET NULL,
    CONSTRAINT fk_tn_spatial_assets_capture FOREIGN KEY (capture_id) REFERENCES tn_spatial_captures (id) ON DELETE SET NULL,
    CONSTRAINT fk_tn_spatial_assets_media FOREIGN KEY (media_id) REFERENCES tn_media_assets (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tn_spatial_relations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scene_id BIGINT UNSIGNED NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL,
    role ENUM('primary', 'before', 'after', 'construction', 'alternative', 'technical') NOT NULL DEFAULT 'primary',
    sort_order INT UNSIGNED NOT NULL DEFAULT 100,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tn_spatial_relations_item (scene_id, entity_type, entity_id, role),
    KEY idx_tn_spatial_relations_entity (entity_type, entity_id, role, sort_order),
    CONSTRAINT fk_tn_spatial_relations_scene FOREIGN KEY (scene_id) REFERENCES tn_spatial_scenes (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tn_spatial_hotspots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id VARCHAR(40) NOT NULL,
    scene_id BIGINT UNSIGNED NOT NULL,
    version_id BIGINT UNSIGNED NULL,
    hotspot_type ENUM('info', 'room', 'feature', 'cta', 'link', 'media', 'measurement', 'navigation') NOT NULL DEFAULT 'info',
    title VARCHAR(180) NOT NULL,
    body TEXT NULL,
    icon VARCHAR(60) NULL,
    position_json JSON NOT NULL,
    target_json JSON NULL,
    action_url VARCHAR(700) NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 100,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tn_spatial_hotspots_public_id (public_id),
    KEY idx_tn_spatial_hotspots_scene (scene_id, is_active, sort_order),
    CONSTRAINT fk_tn_spatial_hotspots_scene FOREIGN KEY (scene_id) REFERENCES tn_spatial_scenes (id) ON DELETE CASCADE,
    CONSTRAINT fk_tn_spatial_hotspots_version FOREIGN KEY (version_id) REFERENCES tn_spatial_versions (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tn_spatial_processing_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id VARCHAR(40) NOT NULL,
    scene_id BIGINT UNSIGNED NOT NULL,
    asset_id BIGINT UNSIGNED NULL,
    job_type ENUM('inspect', 'validate', 'convert', 'optimize', 'thumbnail', 'publish') NOT NULL,
    status ENUM('pending', 'processing', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'pending',
    attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
    progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
    available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at DATETIME NULL,
    lock_token CHAR(32) NULL,
    input_json JSON NULL,
    output_json JSON NULL,
    error_message TEXT NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tn_spatial_jobs_public_id (public_id),
    KEY idx_tn_spatial_jobs_queue (status, available_at, attempts),
    KEY idx_tn_spatial_jobs_scene (scene_id, created_at),
    CONSTRAINT fk_tn_spatial_jobs_scene FOREIGN KEY (scene_id) REFERENCES tn_spatial_scenes (id) ON DELETE CASCADE,
    CONSTRAINT fk_tn_spatial_jobs_asset FOREIGN KEY (asset_id) REFERENCES tn_spatial_assets (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tn_spatial_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scene_id BIGINT UNSIGNED NOT NULL,
    event_type ENUM('view', 'load', 'start', 'complete', 'hotspot', 'ar_open', 'download', 'error') NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    session_key VARCHAR(120) NULL,
    source_page VARCHAR(500) NULL,
    payload_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_tn_spatial_events_scene (scene_id, event_type, created_at),
    KEY idx_tn_spatial_events_user (user_id, created_at),
    CONSTRAINT fk_tn_spatial_events_scene FOREIGN KEY (scene_id) REFERENCES tn_spatial_scenes (id) ON DELETE CASCADE,
    CONSTRAINT fk_tn_spatial_events_user FOREIGN KEY (user_id) REFERENCES tn_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO tn_migrations (migration)
VALUES ('20260823_000017_spatial_core');
