framework:
  secret: '%env(APP_SECRET)%'
  router:
    utf8: true
  serializer:
    enabled: true
    default_context:
      allow_extra_attributes: false
  validation:
    enabled: true
    enable_attributes: true
  php_errors:
    log: true
  session:
    handler_id: null
    save_path: '%env(LEGACY_SESSION_SAVE_PATH)%'
    cookie_secure: auto
    cookie_httponly: true
    cookie_samesite: lax
  cache:
    app: cache.adapter.filesystem
    prefix_seed: cos/symfony
