framework:
  secret: '%env(APP_SECRET)%'
  router:
    utf8: true
  asset_mapper:
    paths:
      - assets/
  serializer:
    enabled: true
    default_context:
      allow_extra_attributes: false
  validation:
    enabled: true
    enable_attributes: true
  php_errors:
    log: true
  session:
    handler_id: null
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    name: COSSESSID
    cookie_secure: auto
    cookie_httponly: true
    cookie_samesite: lax
  cache:
    app: cache.adapter.filesystem
    prefix_seed: cos/symfony
