<?php
declare(strict_types=1);

return [
    'id' => 'growth',
    'name' => 'Growth',
    'version' => '0.7.0',
    'schema_version' => '0.7.0',
    'kernel_constraint' => '>=0.11.0 <0.12.0',
    'description' => 'Opportunity intelligence from observable signals to qualified business opportunity handoff.',
    'icon' => 'radar',
    'dependencies' => [],
    'enabled_by_default' => false,
    'contributions' => [
        'runtime_module_service' => 'growthDomainModule',
        'job_handler_services' => [],
        'api_route_contributor_services' => [],
        'configuration_provisioner_services' => [],
        'extension_services' => [],
        'migration_files' => [
            'app/migrations/20260921_000067_growth_v020_runtime.sql',
            'app/migrations/20260921_000068_growth_v030_account_intelligence.sql',
            'app/migrations/20260922_000069_growth_v040_buying_committee.sql',
            'app/migrations/20260922_000070_growth_v050_signal_collectors.sql',
            'app/migrations/20260922_000071_growth_v060_decision_intelligence.sql',
            'app/migrations/20260922_000072_growth_v070_research_intelligence.sql',
        ],
        'capabilities' => [
            'growth.research.accept',
            'growth.research.brief',
            'growth.research.generate',
            'growth.qualification.policy',
            'growth.candidate.evaluate',
            'growth.candidate.decision_brief',
            'growth.signal.collect',
            'growth.signal.dedupe',
            'growth.signal.ingest',
            'growth.buying_committee.assess',
            'growth.buying_committee.brief',
            'growth.contact.discover',
            'growth.contact.enrich',
            'growth.icp.manage',
            'growth.account.discover',
            'growth.account.enrich',
            'growth.account.score',
            'growth.account.brief',
            'growth.signal.detect',
            'growth.candidate.research',
            'growth.candidate.score',
            'growth.candidate.qualify',
            'growth.handoff.prepare',
            'growth.candidate.monitor',
        ],
    ],
];
