<?php
declare(strict_types=1);

return [
    'id' => 'growth',
    'name' => 'Growth',
    'version' => '0.50.0',
    'schema_version' => '0.50.0',
    'kernel_constraint' => '>=0.11.0 <0.12.0',
    'description' => 'Opportunity intelligence from observable signals to qualified business opportunity handoff.',
    'icon' => 'radar',
    'dependencies' => [],
    'enabled_by_default' => false,
    'contributions' => [
        'runtime_module_service' => 'growthDomainModule',
        'job_handler_services' => [],
        'api_route_contributor_services' => [],
        'configuration_provisioner_services' => [],
        'extension_services' => [
            'web.navigation' => ['growthNavigationContributor'],
            'web.search' => ['growthNavigationContributor'],
            'web.commands' => ['growthNavigationContributor'],
            'web.workspace' => ['growthNavigationContributor'],
        ],
        'migration_files' => [
            'app/migrations/20260921_000067_growth_v020_runtime.sql',
            'app/migrations/20260921_000068_growth_v030_account_intelligence.sql',
            'app/migrations/20260922_000069_growth_v040_buying_committee.sql',
            'app/migrations/20260922_000070_growth_v050_signal_collectors.sql',
            'app/migrations/20260922_000071_growth_v060_decision_intelligence.sql',
            'app/migrations/20260922_000072_growth_v070_research_intelligence.sql',
            'app/migrations/20260922_000073_growth_v080_handoff_protocol.sql',
            'app/migrations/20260922_000074_growth_v0100_api_surface.sql',
            'app/migrations/20260922_000075_growth_v0110_workspace.sql',
            'app/migrations/20260922_000076_growth_v0120_signal_operations.sql',
            'app/migrations/20260922_000077_growth_v0130_external_signal_webhook.sql',
            'app/migrations/20260922_000078_growth_v0140_engagement_intelligence.sql',
            'app/migrations/20260923_000079_growth_v0150_learning_feedback.sql',
            'app/migrations/20260923_000080_growth_v0160_learning_workspace.sql',
            'app/migrations/20260923_000081_growth_v0170_learning_optimization.sql',
            'app/migrations/20260923_000082_growth_v0180_optimization_workspace.sql',
            'app/migrations/20260923_000083_growth_v0190_experiments_attribution.sql',
            'app/migrations/20260923_000084_growth_v0200_experiment_workspace.sql',
            'app/migrations/20260923_000085_growth_v0210_experiment_decision_intelligence.sql',
            'app/migrations/20260923_000086_growth_v0220_engagement_execution_bridge.sql',
            'app/migrations/20260923_000087_growth_v0230_engagement_execution_workspace.sql',
            'app/migrations/20260923_000089_growth_v0240_pre_handoff_execution.sql',
            'app/migrations/20260923_000090_growth_v0250_service_handoff_adapter.sql',
            'app/migrations/20260923_000091_growth_v0260_rss_atom_collector.sql',
            'app/migrations/20260923_000092_growth_v0270_signal_feed_workspace.sql',
            'app/migrations/20260924_000093_growth_v0280_credentialed_json_collector.sql',
            'app/migrations/20260924_000094_growth_v0290_json_signal_source_workspace.sql',
            'app/migrations/20260924_000095_growth_v0300_signal_polling_scheduler.sql',
            'app/migrations/20260924_000096_growth_v0310_polling_operations_workspace.sql',
            'app/migrations/20260924_000097_growth_v0320_collector_health_backoff.sql',
            'app/migrations/20260924_000098_growth_v0330_collector_incidents.sql',
            'app/migrations/20260924_000099_growth_v0340_collector_alert_subscriptions.sql',
            'app/migrations/20260924_000100_growth_v0350_linkedin_call_execution.sql',
            'app/migrations/20260924_000101_growth_v0360_engagement_delivery_feedback.sql',
            'app/migrations/20260924_000102_growth_v0370_outreach_guardrails.sql',
            'app/migrations/20260924_000103_growth_v0380_tenant_outreach_limits.sql',
            'app/migrations/20260924_000104_growth_v0390_channel_outreach_quotas.sql',
            'app/migrations/20260924_000105_growth_v0400_atomic_outreach_capacity.sql',
            'app/migrations/20260924_000106_growth_v0410_outreach_activation_policy.sql',
            'app/migrations/20260925_000107_growth_v0420_autonomous_outreach.sql',
            'app/migrations/20260926_000108_growth_v0430_autonomous_content_review.sql',
            'app/migrations/20260926_000109_growth_v0440_outreach_sequences.sql',
            'app/migrations/20260926_000110_growth_v0450_inbound_responses.sql',
            'app/migrations/20260926_000111_growth_v0460_conversation_routing.sql',
            'app/migrations/20260926_000112_growth_v0470_email_delivery_parity.sql',
            'app/migrations/20260926_000113_growth_v0480_market_discovery.sql',
            'app/migrations/20260926_000114_growth_v0490_cos_for_cos_vertical_slice.sql',
            'app/migrations/20260926_000115_growth_v0500_release_hardening.sql',
        ],
        'capabilities' => [
            'growth.market.resumable_discovery',
            'growth.market.partial_retry',
            'growth.learning.conversation_binding',
            'growth.market.workspace',
            'growth.market.universe.manage',
            'growth.market.discovery',
            'growth.market.automated_sourcing',
            'growth.market.monitoring',
            'growth.market.opportunity_detection',
            'growth.engagement.email_delivery_feedback',
            'growth.engagement.email_complaint_suppression',
            'growth.engagement.email_conversation_feedback',
            'growth.engagement.conversation_routing',
            'growth.engagement.contact_suppression',
            'growth.engagement.routing_target.sales',
            'growth.engagement.routing_target.service',
            'growth.engagement.response_classification',
            'growth.engagement.inbound_response',
            'growth.engagement.response_webhook',
            'growth.engagement.sequence_scheduler',
            'growth.engagement.sequence_state_machine',
            'growth.engagement.sequence_policy',
            'growth.engagement.autonomous_content_scheduler',
            'growth.engagement.autonomous_content_review',
            'growth.engagement.autonomous_content_drafting',
            'growth.engagement.autonomous_trigger',
            'growth.engagement.autonomy_payload_staging',
            'growth.engagement.autonomy_policy',
            'growth.engagement.activation_policy',
            'growth.engagement.atomic_capacity_admission',
            'growth.engagement.channel_quotas',
            'growth.engagement.limit_profile',
            'growth.engagement.execution_limits',
            'growth.engagement.delivery_feedback',
            'growth.engagement.pre_handoff_linkedin_call_execution',
            'growth.signal.polling_alerts',
            'growth.signal.polling_incidents',
            'growth.signal.polling_health',
            'growth.signal.polling_workspace',
            'growth.signal.scheduled_polling',
            'growth.signal.json_source.workspace',
            'growth.signal.collector.credentialed_json',
            'growth.signal.json_source.manage',
            'growth.signal.feed.workspace',
            'growth.signal.collector.rss_atom',
            'growth.signal.feed.manage',
            'growth.handoff.target.service',
            'growth.engagement.pre_handoff_execution',
            'growth.engagement.execution_workspace',
            'growth.engagement.execution',
            'growth.experiments.decision',
            'growth.experiments.workspace',
            'growth.experiments',
            'growth.attribution',
            'growth.learning.optimization_workspace',
            'growth.learning.optimize',
            'growth.learning.workspace',
            'growth.learning.feedback',
            'growth.learning.brief',
            'growth.engagement.intelligence',
            'growth.signal.external_webhook',
            'growth.workspace',
            'growth.signal.operations',
            'growth.api.v1',
            'growth.handoff.target.sales',
            'growth.handoff.dispatch',
            'growth.handoff.brief',
            'growth.handoff.targets',
            'growth.research.accept',
            'growth.research.brief',
            'growth.research.generate',
            'growth.qualification.policy',
            'growth.candidate.evaluate',
            'growth.candidate.decision_brief',
            'growth.signal.collect',
            'growth.signal.dedupe',
            'growth.signal.ingest',
            'growth.buying_committee.assess',
            'growth.buying_committee.brief',
            'growth.contact.discover',
            'growth.contact.enrich',
            'growth.icp.manage',
            'growth.account.discover',
            'growth.account.enrich',
            'growth.account.score',
            'growth.account.brief',
            'growth.signal.detect',
            'growth.candidate.research',
            'growth.candidate.score',
            'growth.candidate.qualify',
            'growth.handoff.prepare',
            'growth.candidate.monitor',
        ],
    ],
];
