<?php
declare(strict_types=1);

return [
    'id'=>'capital_markets',
    'name'=>'Capital Markets',
    'version'=>'0.5.0',
    'schema_version'=>'0.5.0',
    'kernel_constraint'=>'>=0.11.0 <0.12.0',
    'description'=>'Autonomous Capital Markets bounded context with instrument/venue foundation, provider-neutral Market Intelligence and Tokenized Equity H1/H2 research evidence, Edge Funnel and guarded paper execution. Live trading remains disabled.',
    'icon'=>'chart-candlestick',
    'dependencies'=>[],
    'enabled_by_default'=>false,
    'contributions'=>[
        'runtime_module_service'=>'capitalMarketsDomainModule',
        'job_handler_services'=>[],
        'api_route_contributor_services'=>[],
        'configuration_provisioner_services'=>[],
        'extension_services'=>[
            'web.navigation'=>['capitalMarketsNavigationContributor'],
            'web.search'=>['capitalMarketsNavigationContributor'],
            'web.commands'=>['capitalMarketsNavigationContributor'],
            'web.workspace'=>['capitalMarketsNavigationContributor'],
        ],
        'cross_domain_contracts'=>[],
        'migration_files'=>[
            'app/migrations/20261005_000124_capital_markets_foundation.sql',
            'app/migrations/20261006_000125_capital_markets_market_sources.sql',
            'app/migrations/20261006_000126_capital_markets_market_events.sql',
            'app/migrations/20261006_000127_capital_markets_market_state.sql',
            'app/migrations/20261006_000128_capital_markets_tokenized_equity_vertical_slice.sql',
            'app/migrations/20261006_000129_capital_markets_tokenized_equity_research.sql',
        ],
        'capabilities'=>[
            'capital_markets.view',
            'capital_markets.manage',
            'capital_markets.instrument.view',
            'capital_markets.instrument.manage',
            'capital_markets.relationship.view',
            'capital_markets.relationship.manage',
            'capital_markets.venue.view',
            'capital_markets.venue.manage',
            'capital_markets.audit.view',
            'capital_markets.market_data.view',
            'capital_markets.market_data.manage',
            'capital_markets.market_data.source.view',
            'capital_markets.market_data.source.manage',
            'capital_markets.market_data.quality.view',
            'capital_markets.market_data.history.view',
            'capital_markets.market_data.replay.manage',
            'capital_markets.opportunity.view',
            'capital_markets.paper.execute',
        ],
    ],
];
