<?php
declare(strict_types=1);

return [
    'id' => 'documents',
    'name' => 'Documents',
    'version' => '0.1.0',
    'schema_version' => '0.1.0',
    'kernel_constraint' => '>=0.11.0 <0.12.0',
    'description' => 'Tenant-owned document signature request Actions backed by the canonical Platform Documents runtime. A request never means a verified signed document.',
    'icon' => 'file-signature',
    'dependencies' => [],
    'enabled_by_default' => false,
    'contributions' => [
        'runtime_module_service' => 'documentsDomainModule',
        'api_route_contributor_services' => [],
        'configuration_provisioner_services' => [],
        'cross_domain_contracts' => [
            [
                'contract' => 'Domains\\Growth\\Application\\Contract\\GrowthHandoffBoundary',
                'role' => 'requires',
                'counterpart' => 'growth',
                'kind' => 'synchronous_port',
                'purpose' => 'Verify a completed accepted Growth-to-Sales handoff before generating the Sales proposal draft.',
            ],
            [
                'contract' => 'Domains\\Sales\\Application\\Contract\\SalesWorkspaceReadModelInterface',
                'role' => 'requires',
                'counterpart' => 'sales',
                'kind' => 'synchronous_port',
                'purpose' => 'Read a tenant-owned native Sales Lead without accessing Sales persistence.',
            ],
        ],
        'migration_files' => [],
        'capability_contracts' => [
            [
                'id' => 'documents.proposal.prepare',
                'version' => '1.0.0',
                'owner_domain' => 'documents',
                'kind' => 'command',
                'input_schema' => 'resources/contracts/documents/prepare-proposal-input.schema.json',
                'output_schema' => 'resources/contracts/documents/prepare-proposal-output.schema.json',
                'execution_binding' => 'action:documents.proposal.prepare',
                'async' => true,
                'side_effect_level' => 'external',
                'permission' => 'cos.tenant.manage',
                'approval_policy' => 'required',
                'idempotency' => 'required',
                'timeout_policy' => ['seconds' => 90],
                'retry_policy' => ['max_attempts' => 1],
                'failure_contract' => 'Template creation and lead attachment can partially complete; reconcile native receipts before manual recovery, no blind replay.',
                'lifecycle' => 'experimental',
                'tests' => ['tests/unit/federation_documents_proposal_draft.php'],
                'documentation' => 'docs/03-architecture/cos-federation-goal-execution-foundation.md',
            ],
            [
                'id' => 'documents.signature.sign',
                'version' => '1.0.0',
                'owner_domain' => 'documents',
                'kind' => 'command',
                'input_schema' => 'resources/contracts/documents/verified-signature-input.schema.json',
                'output_schema' => 'resources/contracts/documents/verified-signature-output.schema.json',
                'execution_binding' => 'action:documents.signature.sign',
                'async' => true,
                'side_effect_level' => 'external',
                'permission' => 'cos.tenant.manage',
                'approval_policy' => 'required',
                'idempotency' => 'required',
                'timeout_policy' => ['seconds'=>90],
                'retry_policy' => ['max_attempts'=>1],
                'failure_contract' => 'No provider proof, expired proof or ambiguous signature write requires manual reconciliation; never auto-retry.',
                'lifecycle' => 'experimental',
                'tests' => ['tests/unit/federation_documents_signed_attestation.php','tests/architecture/federation_execution_authorization.php'],
                'documentation' => 'docs/03-architecture/federation-trusted-goal-outcomes.md',
            ],

            [
                'id' => 'documents.signature.request',
                'version' => '1.0.0',
                'owner_domain' => 'documents',
                'kind' => 'command',
                'input_schema' => 'resources/contracts/documents/request-signature-input.schema.json',
                'output_schema' => 'resources/contracts/documents/request-signature-output.schema.json',
                'execution_binding' => 'action:documents.signature.request',
                'async' => true,
                'side_effect_level' => 'external',
                'permission' => 'cos.tenant.manage',
                'approval_policy' => 'required',
                'idempotency' => 'required',
                'timeout_policy' => ['seconds' => 90],
                'retry_policy' => ['max_attempts' => 1],
                'failure_contract' => 'Ambiguous signature requests require idempotency-key reconciliation; no blind external retry.',
                'lifecycle' => 'experimental',
                'tests' => ['tests/unit/federation_documents_signature_request.php', 'tests/architecture/federation_execution_authorization.php'],
                'documentation' => 'docs/03-architecture/federation-trusted-goal-outcomes.md',
            ],
        ],
        'capabilities' => ['documents.signature.request','documents.signature.sign','documents.proposal.prepare'],
    ],
];
